apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil-gitlab
  namespace: gitlab
  labels:
    app: wil-playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wil-playground
  template:
    metadata:
      labels:
        app: wil-playground
    spec:
      containers:
      - name: wil-gitlab
        image: wil42/playground:v1
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: wil-gitlab
spec:
  selector:
    app: wil-playground
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888