# VIRTUALBOX SETTINGS
MEMORY = 1024 # or 512
CPU = 1

# MACHINES SETTINGS
S_NAME = "elgruskoS" # Don't forget to update the pseudo.
S_IP = "192.168.56.110"

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = CPU
    vb.memory = MEMORY
  end

  config.vm.box = "generic/debian10"
  config.vm.box_url = "https://app.vagrantup.com/generic/boxes/debian10"
  # config.vm.provision "shell", path: "./scripts/debian.sh"

  config.vm.define S_NAME do |s|
    s.vm.hostname = S_NAME
    s.vm.network "private_network", ip: S_IP
    s.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--name", S_NAME]
    end
    s.vm.provision "shell", path: "./scripts/server.sh", args: [S_IP]
    s.vm.synced_folder "./confs", "/vagrant", type: "virtualbox"
  end

end
